### ISSUE TITLE
Grant statuses have different capitalizations

### ISSUE THREAD

**Issue by cameronblandford** [eclipse-pass/pass-ui#247]
![image](https://user-images.githubusercontent.com/7365276/39646505-a75abe5c-4fa9-11e8-95fd-4bc87a591b77.png)

**Comment by jabrah** [comment]
Sorry I missed this ticket - these values will be obtained either from the backend or otherwise external from the UI. According to documentation, if present, `grant.awardStatus` can take one of three values (https://github.com/OA-PASS/pass-data-model/blob/master/documentation/Grant.md#status-options), so the previously capitalized grant status we saw before were incorrect.

The merged changes certainly look fine for the demos, but the display logic will need to be modified at some point to account for the actual values.
